// Liste exhaustive des stats réellement présentes sur au moins un cube
// (vérifiée via `SELECT DISTINCT cle_stat, libelle FROM StatCube` — 35 stats).
// Ne pas ajouter de clé ici sans revérifier en base, pour ne pas afficher une
// case de filtre qui ne matchera jamais aucun cube.
export const STATS_CUBES = [
  { cle: 'AGILITE', libelle: 'Agilité' },
  { cle: 'CHANCE', libelle: 'Chance' },
  { cle: 'DOMMAGES', libelle: 'Dommages' },
  { cle: 'DO_AIR', libelle: 'Dommages Air' },
  { cle: 'DO_CRIT', libelle: 'Dommages Critiques' },
  { cle: 'DO_EAU', libelle: 'Dommages Eau' },
  { cle: 'DO_FEU', libelle: 'Dommages Feu' },
  { cle: 'DO_POU', libelle: 'Dommages Poussée' },
  { cle: 'DO_TERRE', libelle: 'Dommages Terre' },
  { cle: 'ESQUIVE_PA', libelle: 'Esquive PA' },
  { cle: 'ESQUIVE_PM', libelle: 'Esquive PM' },
  { cle: 'FORCE', libelle: 'Force' },
  { cle: 'FUITE', libelle: 'Fuite' },
  { cle: 'INITIATIVE', libelle: 'Initiative' },
  { cle: 'INTELLIGENCE', libelle: 'Intelligence' },
  { cle: 'INVOCATION', libelle: 'Invocation' },
  { cle: 'PA', libelle: 'PA' },
  { cle: 'PM', libelle: 'PM' },
  { cle: 'PO', libelle: 'PO' },
  { cle: 'PUISSANCE', libelle: 'Puissance' },
  { cle: 'RES_AIR', libelle: 'Résistance Air' },
  { cle: 'RES_CRIT', libelle: 'Résistance Critiques' },
  { cle: 'RES_EAU', libelle: 'Résistance Eau' },
  { cle: 'RES_FEU', libelle: 'Résistance Feu' },
  { cle: 'RES_NEUTRE', libelle: 'Résistance Neutre' },
  { cle: 'RES_POU', libelle: 'Résistance Poussée' },
  { cle: 'RES_TERRE', libelle: 'Résistance Terre' },
  { cle: 'SAGESSE', libelle: 'Sagesse' },
  { cle: 'SOIN', libelle: 'Soin' },
  { cle: 'VITALITE', libelle: 'Vitalité' },
  { cle: '%_COUP_CRITIQUE', libelle: '% Critique' },
  { cle: '%_RES_AIR', libelle: '% Résistance Air' },
  { cle: '%_RES_EAU', libelle: '% Résistance Eau' },
  { cle: '%_RES_FEU', libelle: '% Résistance Feu' },
  { cle: '%_RES_NEUTRE', libelle: '% Résistance Neutre' },
  { cle: '%_RES_TERRE', libelle: '% Résistance Terre' },
];
